### ISSUE TITLE
Please add FIPS arguments

### ISSUE THREAD

**Issue by xnox** [canonical/secboot#264]
Some of the cryptsetup options are not FIPS compliant, thus please add detection for FIPS mode and use more FIPS appropriate options.

I will provide a pull request, filing this just to not forget.

**Comment by chrisccoulson** [comment]
I wonder if this is fixed now by https://github.com/snapcore/secboot/pull/286

**Comment by chrisccoulson** [comment]
Closing this one for now due to https://github.com/canonical/secboot/pull/286, which switched the LUKS2 keyslots to pbkdf2 without any customizability. The long term vision here is to have a raw keyslot with no KDF as part of the LUKS2 specification, as there's no cryptographic benefit from taking one 32-byte recovered key (eg, from the TPM) and deriving another 32-byte key from it in order to obtain the volume key from the binary keyslot area, but unfortunately, LUKS2 and cryptsetup are based around the concept of low-entropy passphrases.

Where KDFs are useful are TPM + PIN, which will be harcoded to PBKDF2 by default (although it currently uses go's package for this).

TPM + passphrases work slightly different and will permit the use of Argon2id (the default), or Argon2i or PBKDF2 as options. The behaviour differences here are because we exploit the extra entropy from a passphrase to use Argon2id (~42 bits I believe is the average entropy for a "reasonable" passphrase) to derive an intermediate key, which is then HKDF-Expanded to 3 other keys - the authorization value for the TPM, and a symmetric key and nonce to perform an additional encryption of the TPM encrypted payload outside of the TPM. This provides additional hardening in the event of a TPM compromise that might enable an adversary to obtain secrets from it without authentication (eg, a firmware bug, or imagine a government agency asks a TPM device manufacturer to provide them with custom firmware to do this for them - they would still have to brute force a passphrase using a secure key derivation function in order to obtain the rest of the cryptographic material required to unlock a storage container - it's not feasible to recover the other derived keys from the recovered authorization value stored inside the `TPMT_SENSITIVE` structure of any sealed object in the event that it could be accessed without authentication). For this reason TPM + passphrases will default to a costly, memory hard key derivation function (the hybrid mode of Argon2) where the parameters are benchmarked similarly to how they are in cryptsetup -  to achieve an execution time to 2 seconds,. In the normal circumstance, the TPM authentication and its associated dictionary attack logic prevents the passphrase from being brute-forced offline, assuming that the TPM is good.

In the case of TPM+PIN (where a PIN is a PIN in the literal sense - base 10 characters in the range of 0-9), and because an 8 digit PIN only has an entropy of a little over 23 bits, the additional protections we apply for passphrases add minimal value here other than making the boot experience seem slower than it needs to be. 23 bits of entropy is not going to be difficult for an adversary who has compromised the TPM to crack regardless of the key derivation used. For this reason, PINs are used only for authentication with the TPM - they don't provide the additional hardening that passphrases will provide such as providing additional cryptographic material in order to recover the final unlock key. As a consequences, TPM+PIN will always use PBKDF2 to derive the TPM's authorization value from the user supplied PIN, and will be tuned with much faster parameters (~100ms - assuming no TPM vulnerability or bug, they still can't be brute-forced offline and still benefit from the TPM's dictionary attack logic).

The eventual snapd API for adding keys will permit the client to choose which KDF is used for passphrases (Argon2id, Argon2i, or PBKDF2).

**Comment by chrisccoulson** [comment]
> Closing this one for now due to #286, which switched the LUKS2 keyslots to pbkdf2 without any customizability. The long term vision here is to have a raw keyslot with no KDF as part of the LUKS2 specification, as there's no cryptographic benefit from taking one 32-byte recovered key (eg, from the TPM) and deriving another 32-byte key from it in order to obtain the volume key from the binary keyslot area, but unfortunately, LUKS2 and cryptsetup are based around the concept of low-entropy passphrases.
> 
> Where KDFs are useful are TPM + PIN, which will be harcoded to PBKDF2 by default (although it currently uses go's package for this).
> 
> TPM + passphrases work slightly different and will permit the use of Argon2id (the default), or Argon2i or PBKDF2 as options. The behaviour differences here are because we exploit the extra entropy from a passphrase to use Argon2id (~42 bits I believe is the average entropy for a "reasonable" passphrase) to derive an intermediate key, which is then HKDF-Expanded to 3 other keys - the authorization value for the TPM, and a symmetric key and nonce to perform an additional encryption of the TPM encrypted payload outside of the TPM. This provides additional hardening in the event of a TPM compromise that might enable an adversary to obtain secrets from it without authentication (eg, a firmware bug, or imagine a government agency coerces a TPM device manufacturer to provide them with custom firmware to do this for them - they would still have to brute force a passphrase using a secure key derivation function in order to obtain the rest of the cryptographic material required to unlock a storage container in this case - and it's not feasible to recover the other derived keys from the recovered authorization value stored inside the `TPMT_SENSITIVE` structure of any sealed object in the event that it could be accessed without authentication). For this reason TPM + passphrases will default to a costly, memory hard key derivation function (the hybrid mode of Argon2) where the parameters are benchmarked similarly to how they are in cryptsetup - to achieve an execution time to 2 seconds,. In the normal circumstance, the TPM authentication and its associated dictionary attack logic prevents the passphrase from being brute-forced offline, assuming that the TPM is good.
> 
> In the case of TPM + PIN (where a PIN is a PIN in the literal sense - base 10 characters in the range of 0-9), and because an 8 digit PIN only has an entropy of a little over 23 bits, the additional protections we apply for passphrases contribute minimal value here other than making the boot experience seem slower than it needs to be. 23 bits of entropy is not going to be difficult for an adversary who has compromised the TPM to crack regardless of the key derivation used. For this reason, PINs are used only for authentication with the TPM - they don't provide the additional hardening that passphrases will provide such as providing additional cryptographic material in order to recover the final unlock key. As a consequences, TPM + PIN keys will always use PBKDF2 to derive the TPM's authorization value from the user supplied PIN, and will be tuned with much faster parameters (~100ms - assuming no TPM vulnerability or bug, they still can't be brute-forced offline and still benefit from the TPM's dictionary attack logic).
> 
> The eventual snapd API for adding keys will permit the client to choose which KDF is used for passphrases (Argon2id, Argon2i, or PBKDF2).

Of course, snapd could default to PBKDF2 for TPM + passphrase keys when the system is in FIPS mode, and the new API could restrict the usage of Argon2i and Argon2id in these modes, although I don't think that this is specced out anywhere yet.
